# Generated by Django 3.2.6 on 2021-08-22 10:07

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('middleName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('secondPhoneNumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=200)),
                ('stu_roll', models.IntegerField()),
                ('stu_email', models.EmailField(max_length=254, null=True)),
                ('std_num', models.IntegerField(default=1, null=True)),
                ('just_name', models.CharField(blank=True, default='Ali', max_length=200)),
                ('status', models.BooleanField(blank=True, default=True)),
            ],
        ),
    ]
