# Generated by Django 3.2.6 on 2021-08-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210822_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.IntegerField()),
                ('password', models.CharField(max_length=100)),
                ('password1', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='std_num',
            field=models.IntegerField(default=1),
        ),
    ]
